// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protob/eventstore.proto

package protob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScopeChoice int32

const (
	ScopeChoice_Instance ScopeChoice = 0
	ScopeChoice_Bridge   ScopeChoice = 1
	ScopeChoice_Global   ScopeChoice = 2
)

var ScopeChoice_name = map[int32]string{
	0: "Instance",
	1: "Bridge",
	2: "Global",
}

var ScopeChoice_value = map[string]int32{
	"Instance": 0,
	"Bridge":   1,
	"Global":   2,
}

func (x ScopeChoice) String() string {
	return proto.EnumName(ScopeChoice_name, int32(x))
}

func (ScopeChoice) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{0}
}

type ScopeType struct {
	Type                 ScopeChoice `protobuf:"varint,1,opt,name=type,proto3,enum=protob.ScopeChoice" json:"type,omitempty"`
	Bridge               string      `protobuf:"bytes,2,opt,name=bridge,proto3" json:"bridge,omitempty"`
	Instance             string      `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ScopeType) Reset()         { *m = ScopeType{} }
func (m *ScopeType) String() string { return proto.CompactTextString(m) }
func (*ScopeType) ProtoMessage()    {}
func (*ScopeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{0}
}

func (m *ScopeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopeType.Unmarshal(m, b)
}
func (m *ScopeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopeType.Marshal(b, m, deterministic)
}
func (m *ScopeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopeType.Merge(m, src)
}
func (m *ScopeType) XXX_Size() int {
	return xxx_messageInfo_ScopeType.Size(m)
}
func (m *ScopeType) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopeType.DiscardUnknown(m)
}

var xxx_messageInfo_ScopeType proto.InternalMessageInfo

func (m *ScopeType) GetType() ScopeChoice {
	if m != nil {
		return m.Type
	}
	return ScopeChoice_Instance
}

func (m *ScopeType) GetBridge() string {
	if m != nil {
		return m.Bridge
	}
	return ""
}

func (m *ScopeType) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

type LocationType struct {
	Scope                *ScopeType `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LocationType) Reset()         { *m = LocationType{} }
func (m *LocationType) String() string { return proto.CompactTextString(m) }
func (*LocationType) ProtoMessage()    {}
func (*LocationType) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{1}
}

func (m *LocationType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationType.Unmarshal(m, b)
}
func (m *LocationType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationType.Marshal(b, m, deterministic)
}
func (m *LocationType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationType.Merge(m, src)
}
func (m *LocationType) XXX_Size() int {
	return xxx_messageInfo_LocationType.Size(m)
}
func (m *LocationType) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationType.DiscardUnknown(m)
}

var xxx_messageInfo_LocationType proto.InternalMessageInfo

func (m *LocationType) GetScope() *ScopeType {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *LocationType) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SaveRequest struct {
	Location             *LocationType `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Ttl                  int32         `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Value                []byte        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{2}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetLocation() *LocationType {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SaveRequest) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *SaveRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{3}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

type LoadRequest struct {
	Location             *LocationType `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{4}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetLocation() *LocationType {
	if m != nil {
		return m.Location
	}
	return nil
}

type LoadResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{5}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DeleteRequest struct {
	Location             *LocationType `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{6}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetLocation() *LocationType {
	if m != nil {
		return m.Location
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aeb551742d07b8c, []int{7}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protob.ScopeChoice", ScopeChoice_name, ScopeChoice_value)
	proto.RegisterType((*ScopeType)(nil), "protob.ScopeType")
	proto.RegisterType((*LocationType)(nil), "protob.LocationType")
	proto.RegisterType((*SaveRequest)(nil), "protob.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "protob.SaveResponse")
	proto.RegisterType((*LoadRequest)(nil), "protob.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "protob.LoadResponse")
	proto.RegisterType((*DeleteRequest)(nil), "protob.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "protob.DeleteResponse")
}

func init() {
	proto.RegisterFile("pkg/protob/eventstore.proto", fileDescriptor_2aeb551742d07b8c)
}

var fileDescriptor_2aeb551742d07b8c = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x4f, 0xbb, 0x40,
	0x10, 0x2d, 0xfd, 0x43, 0xda, 0x29, 0xbf, 0x86, 0xdf, 0x8a, 0x4d, 0x83, 0x17, 0x43, 0x4c, 0x34,
	0xc6, 0x80, 0x69, 0x4f, 0x9e, 0x8c, 0x55, 0x63, 0x9a, 0xf4, 0x44, 0x3d, 0x79, 0x03, 0x3a, 0x01,
	0x52, 0xca, 0x22, 0x6c, 0x9b, 0xf4, 0x63, 0xf9, 0x0d, 0xed, 0xb2, 0x50, 0xc0, 0x63, 0x4f, 0xec,
	0xce, 0xbc, 0x79, 0x8f, 0x7d, 0x33, 0x03, 0x57, 0xc9, 0xc6, 0xb7, 0x92, 0x94, 0x32, 0xea, 0x5a,
	0xb8, 0xc7, 0x98, 0x65, 0x8c, 0xa6, 0x68, 0xe6, 0x11, 0x22, 0x8b, 0x84, 0x11, 0xc0, 0x60, 0xe5,
	0xd1, 0x04, 0x3f, 0x0f, 0x09, 0x92, 0x5b, 0xe8, 0xb2, 0xe3, 0x77, 0x22, 0x5d, 0x4b, 0x77, 0xa3,
	0xe9, 0x85, 0x80, 0xba, 0x66, 0x0e, 0x78, 0x0d, 0x68, 0xe8, 0xa1, 0x9d, 0x03, 0xc8, 0x18, 0x64,
	0x37, 0x0d, 0xd7, 0x3e, 0x4e, 0xda, 0x47, 0xe8, 0xc0, 0x2e, 0x6e, 0x44, 0x87, 0x7e, 0x18, 0x67,
	0xcc, 0x89, 0x3d, 0x9c, 0x74, 0xf2, 0xcc, 0xe9, 0x6e, 0x2c, 0x40, 0x59, 0x52, 0xcf, 0x61, 0x21,
	0x8d, 0x0b, 0xb1, 0x5e, 0xc6, 0x89, 0x73, 0xb5, 0xe1, 0xf4, 0x7f, 0x43, 0x8d, 0x23, 0x6c, 0x91,
	0x27, 0x2a, 0x74, 0x36, 0x78, 0x28, 0x94, 0xf8, 0xd1, 0xf0, 0x61, 0xb8, 0x72, 0xf6, 0x68, 0xe3,
	0xf7, 0x0e, 0x33, 0x46, 0x1e, 0xa1, 0x1f, 0x15, 0xcc, 0x05, 0x99, 0x56, 0x92, 0xd5, 0x15, 0xed,
	0x13, 0x8a, 0x53, 0x32, 0x16, 0xe5, 0x94, 0x3d, 0x9b, 0x1f, 0x89, 0x06, 0xbd, 0xbd, 0x13, 0xed,
	0xc4, 0x6f, 0x2b, 0xb6, 0xb8, 0x18, 0x23, 0x50, 0x84, 0x50, 0x96, 0xd0, 0x38, 0x43, 0xe3, 0x19,
	0x86, 0x4b, 0xea, 0xac, 0xcf, 0x16, 0x36, 0x6e, 0xb8, 0x09, 0x9c, 0x40, 0x10, 0x56, 0xb2, 0x52,
	0x5d, 0xf6, 0x05, 0xfe, 0xbd, 0x61, 0x84, 0xec, 0xfc, 0x17, 0x1a, 0x2a, 0x8c, 0x4a, 0x0a, 0x21,
	0x75, 0x3f, 0x3b, 0x9a, 0x56, 0x35, 0x92, 0x28, 0xd0, 0x5f, 0x14, 0xad, 0x51, 0x5b, 0x04, 0x40,
	0x9e, 0xe7, 0x2d, 0x54, 0x25, 0x7e, 0xfe, 0x88, 0xa8, 0xeb, 0x44, 0x6a, 0x7b, 0xfa, 0x23, 0x01,
	0xbc, 0xf3, 0xd9, 0x59, 0xf1, 0xd9, 0x21, 0x33, 0xe8, 0x72, 0x3f, 0x48, 0x35, 0x1a, 0x55, 0x1b,
	0x74, 0xad, 0x19, 0x2c, 0x2c, 0x6b, 0xf1, 0x22, 0xfe, 0xe6, 0xaa, 0xa8, 0x66, 0xa1, 0xae, 0x35,
	0x83, 0xa7, 0xa2, 0x27, 0x90, 0xc5, 0xff, 0x93, 0xcb, 0x12, 0xd1, 0xb0, 0x44, 0x1f, 0xff, 0x0d,
	0x97, 0xa5, 0x73, 0xf3, 0xeb, 0xc1, 0x0f, 0x59, 0xb0, 0x73, 0x4d, 0x8f, 0x6e, 0x2d, 0x96, 0x86,
	0xbe, 0x8f, 0xe9, 0x16, 0xb3, 0xa0, 0xb6, 0x05, 0x56, 0xb5, 0x1b, 0xae, 0x58, 0x85, 0xd9, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xca, 0x86, 0xc6, 0x30, 0x03, 0x00, 0x00,
}
