// +build !ignore_autogenerated

/*
Copyright (c) 2020 TriggerMesh Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryStore) DeepCopyInto(out *InMemoryStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryStore.
func (in *InMemoryStore) DeepCopy() *InMemoryStore {
	if in == nil {
		return nil
	}
	out := new(InMemoryStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InMemoryStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryStoreList) DeepCopyInto(out *InMemoryStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InMemoryStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryStoreList.
func (in *InMemoryStoreList) DeepCopy() *InMemoryStoreList {
	if in == nil {
		return nil
	}
	out := new(InMemoryStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InMemoryStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryStoreSpec) DeepCopyInto(out *InMemoryStoreSpec) {
	*out = *in
	if in.DefaultGlobalTTL != nil {
		in, out := &in.DefaultGlobalTTL, &out.DefaultGlobalTTL
		*out = new(int)
		**out = **in
	}
	if in.DefaultBridgeTTL != nil {
		in, out := &in.DefaultBridgeTTL, &out.DefaultBridgeTTL
		*out = new(int)
		**out = **in
	}
	if in.DefaultInstanceTTL != nil {
		in, out := &in.DefaultInstanceTTL, &out.DefaultInstanceTTL
		*out = new(int)
		**out = **in
	}
	if in.DefaultExpiredGCPeriod != nil {
		in, out := &in.DefaultExpiredGCPeriod, &out.DefaultExpiredGCPeriod
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryStoreSpec.
func (in *InMemoryStoreSpec) DeepCopy() *InMemoryStoreSpec {
	if in == nil {
		return nil
	}
	out := new(InMemoryStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InMemoryStoreStatus) DeepCopyInto(out *InMemoryStoreStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.AddressStatus.DeepCopyInto(&out.AddressStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InMemoryStoreStatus.
func (in *InMemoryStoreStatus) DeepCopy() *InMemoryStoreStatus {
	if in == nil {
		return nil
	}
	out := new(InMemoryStoreStatus)
	in.DeepCopyInto(out)
	return out
}
